const PRIMARY_COLOR_PALETTE = "p";
const INPUT_FOCUS_BORDER_COLOR = "p.500";
const CONTAINER_BORDER_RADIUS = [16, null, 8];
const CONTENT_BORDER_RADIUS = [12, null, 6];

export {
  PRIMARY_COLOR_PALETTE,
  INPUT_FOCUS_BORDER_COLOR,
  CONTAINER_BORDER_RADIUS,
  CONTENT_BORDER_RADIUS,
};
