const PRIMARY_COLOR_PALETTE = "p";
const INPUT_BORDER_COLOR_FOCUS = "p.500";
const CONTAINER_BORDER_RADIUS = [16, null, 8];
const CONTENT_BORDER_RADIUS = [12, null, 6];

export {
  PRIMARY_COLOR_PALETTE,
  INPUT_BORDER_COLOR_FOCUS,
  CONTAINER_BORDER_RADIUS,
  CONTENT_BORDER_RADIUS,
};
